# Generated by Django 3.2.6 on 2021-09-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_up_comming_external_site'),
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('1', '7AM - 10AM'), ('2', '11AM - 2PM'), ('3', '3PM - 6PM'), ('4', '7PM - 10PM')], default='1', max_length=100)),
                ('day', models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Thursday'), ('4', 'Friday'), ('4', 'Saturday')], default='1', max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.now_showing')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='movies',
            field=models.ManyToManyField(through='halls.Movie_Timing', to='movies.Now_Showing'),
        ),
    ]
