# Generated by Django 3.2.6 on 2021-09-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_up_comming_external_site'),
        ('halls', '0002_auto_20210901_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Timing',
            new_name='Movie_Hall',
        ),
    ]
