# Generated by Django 3.2.6 on 2021-09-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_up_comming_external_site'),
        ('halls', '0003_rename_movie_timing_movie_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='h_Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='movie_hall',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='halls.hall'),
        ),
        migrations.AlterField(
            model_name='movie_hall',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.now_showing'),
        ),
    ]
