# Generated by Django 3.2.6 on 2021-09-03 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_auto_20210902_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_hall',
            name='day',
        ),
        migrations.AddField(
            model_name='movie_hall',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 3)),
        ),
    ]
