# Generated by Django 3.2.6 on 2021-09-03 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_auto_20210903_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_hall',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
