# Generated by Django 3.2.6 on 2021-09-03 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0008_alter_movie_hall_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_hall',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
