# Generated by Django 3.2.6 on 2021-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0009_alter_movie_hall_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_hall',
            name='discount',
            field=models.BooleanField(default=True),
        ),
    ]
