# Generated by Django 3.2.6 on 2021-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0010_movie_hall_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_hall',
            name='booked',
            field=models.TextField(null=True),
        ),
    ]
