# Generated by Django 3.2.6 on 2021-09-04 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0011_movie_hall_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_hall',
            name='booked',
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=2)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_movie', to='halls.movie_hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie_hall',
            name='booked',
            field=models.ManyToManyField(through='halls.Booked', to=settings.AUTH_USER_MODEL),
        ),
    ]
