# Generated by Django 3.2.6 on 2021-09-04 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_delete_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0012_auto_20210904_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(max_length=2, null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_given', to='tickets.categories')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_movie', to='halls.movie_hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booked',
        ),
        migrations.AlterField(
            model_name='movie_hall',
            name='booked',
            field=models.ManyToManyField(through='halls.Ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
