# Generated by Django 3.2.6 on 2021-09-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_up_comming_external_site'),
        ('halls', '0012_auto_20210908_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='movies',
            field=models.ManyToManyField(blank=True, through='halls.Movie_Hall', to='movies.Now_Showing'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Canceled', 'Canceled'), ('Expired', 'Expired')], default=1, max_length=100),
        ),
    ]
