# Generated by Django 3.2.6 on 2021-09-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0013_auto_20210909_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Purchased', 'Purchased'), ('Canceled', 'Canceled'), ('Booked', 'Booked')], default='Booked', max_length=100),
        ),
    ]
