# Generated by Django 3.2.6 on 2021-09-09 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
        ('halls', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.categories'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.movie_hall'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Purchased', 'Purchased'), ('Canceled', 'Canceled'), ('Booked', 'Booked')], default='Booked', max_length=100)),
                ('seats', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.categories')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.movie_hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
