# Generated by Django 3.2.6 on 2021-09-09 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0016_purchase_payment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_hall',
            name='booked',
            field=models.ManyToManyField(blank=True, through='halls.Ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
