# Generated by Django 3.2.6 on 2021-09-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0018_alter_hall_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='halls.category'),
        ),
    ]
