# Generated by Django 3.2.6 on 2021-08-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210820_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up_Comming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='static/images/movies')),
                ('trailer', models.URLField()),
                ('summary', models.CharField(max_length=500)),
                ('desc', models.TextField(default='Summary')),
                ('actors', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Now_Showing',
        ),
    ]
