# Generated by Django 3.2.6 on 2021-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210821_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='now_showing',
            name='background',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='up_comming',
            name='background',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
