# Generated by Django 3.2.6 on 2021-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210824_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_comming',
            name='external_site',
            field=models.URLField(null=True),
        ),
    ]
