# Generated by Django 3.2.6 on 2021-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210910_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now_showing',
            name='poster',
            field=models.ImageField(upload_to='static/images/movies'),
        ),
        migrations.AlterField(
            model_name='up_comming',
            name='poster',
            field=models.ImageField(upload_to='static/images/movies'),
        ),
    ]
