# Generated by Django 3.2.6 on 2021-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210910_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now_showing',
            name='background',
            field=models.ImageField(null=True, upload_to='static/images/movies'),
        ),
        migrations.AlterField(
            model_name='up_comming',
            name='background',
            field=models.ImageField(null=True, upload_to='static/images/movies'),
        ),
    ]
