# Generated by Django 3.2.6 on 2021-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
