# Generated by Django 3.2.6 on 2021-09-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_categories_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='valid',
        ),
    ]
