# Generated by Django 3.2.6 on 2021-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('f_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(blank=True, max_length=20, null=True)),
                ('l_name', models.CharField(max_length=20)),
                ('profile', models.ImageField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateField()),
            ],
        ),
    ]
