# Generated by Django 3.2.6 on 2021-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Sundarijal', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(default='Kathmandu', max_length=30),
        ),
    ]
